name: testing

on: 
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18.13.0'
        cache: 'npm'
    - run: npm install
    - run:  npm --version
  